app/add/views.py
from flask import Blueprint, flash,render_template, session
from flask_login import login_required
from ..models import Asset, db, Appointment, Record, RecordTwo
from .forms import AddForm, AppointForm, RecordForm
from datetime import datetime
from .email import send_email
from . import predict

add_bp = Blueprint("add_bp", __name__, template_folder="templates",
                    static_folder="static")


@add_bp.route("/", methods=["POST", "GET"])
@login_required
def add():
    add_form = AddForm()
    
    if add_form.validate_on_submit():
        asset = Asset(asset_tag=1234, name=add_form.name.data, type=add_form.type.data,
                        item_discription=add_form.item_discription.data, condition=add_form.condition.data,
                        serial=add_form.serial.data, date_manufactured=add_form.date_manufactured.data,
                        cost=add_form.cost.data, purchase_date=add_form.purchase_date.data)
        
        db.session.add(asset)
        db.session.commit()

        flash("Asset added succesfully", category="success")
        
    return render_template("add/add.html", form=add_form)


@add_bp.route("/add_med", methods=["GET", "POST"])
def add_med():
    form = RecordForm()
    name = session.get("name")
    is_admin = session.get("is_admin")
    last_name = session.get("last_name")

    if form.validate_on_submit():
        record = Record(
            name = form.name.data,
            age = form.age.data,
            address = form.address.data,
            blood_type = form.blood_type.data,
            number_children = form.number_children.data,
            last_birth = form.last_birth.data,
            allergies = form.allergies.data,
            medical_condition = form.medical_condition.data
        )

        db.session.add(record)
        db.session.commit()

        flash("Record added", category="success")
        
    return render_template("add/add_med.html", form=form, name=name, last_name=last_name, admin=is_admin)

@add_bp.route("/checkup", methods=["GET", "POST"])
def checkup():
    form = AppointForm()
    name = session.get("name")
    is_admin = session.get("is_admin")
    last_name = session.get("last_name")

    if form.validate_on_submit():
        tyme = get_date()
        appointment = Appointment(
            name = form.name.data,
            mobile = form.mobile.data,
            email = form.email.data,
            date = tyme
        )

        db.session.add(appointment)
        db.session.commit()

        flash("appointment will be booked and emailed to you shortly", category="success")
        send_email(tyme, form.email.data)

    return render_template("add/checkup.html", form=form, name=name, last_name=last_name, admin=is_admin)

@add_bp.route("/doctor", methods=["GET", "POST"])
def doctor():
    form = AppointForm()
    name = session.get("name")
    is_admin = session.get("is_admin")
    last_name = session.get("last_name")

    if form.validate_on_submit():
        tyme = get_date()
        appointment = Appointment(
            name = form.name.data,
            mobile = form.mobile.data,
            email = form.email.data,
            date = tyme
        )

        db.session.add(appointment)
        db.session.commit()

        flash("appointment will be booked and emailed to you shortly", category="success")
        send_email(tyme, form.email.data)

    return render_template("add/doctor.html", form=form, name=name, last_name=last_name, admin=is_admin)

@add_bp.route("/new_med", methods=["GET", "POST"])
def new_med():
    form = RecordForm()
    name = session.get("name")
    is_admin = session.get("is_admin")
    last_name = session.get("last_name")

    if form.validate_on_submit():
        record = Record(
            name = form.name.data,
            age = form.age.data,
            address = form.address.data,
            blood_type = form.blood_type.data,
            number_children = form.number_children.data,
            last_birth = form.last_birth.data,
            allergies = form.allergies.data,
            medical_condition = form.medical_condition.data
        )
        data  = [
            form.age.data,
            form.systolic_BP.data,
            form.diastolic_BP.data,
            form.blood_sugar.data,
            form.body_temp.data,
            form.heart_rate.data,
        ]
         
        record2 = RecordTwo(
            name = form.name.data,
            age = form.age.data,
            address = form.address.data,
            blood_type = form.blood_type.data,
            systolic_BP = form.systolic_BP.data,
            diastolic_BP = form.diastolic_BP.data,
            blood_sugar = form.blood_sugar.data,
            body_temp = form.body_temp.data,
            heart_rate = form.heart_rate.data,
            risk_level = predict.get_prediction(data),
            number_children = form.number_children.data,
            last_birth = form.last_birth.data,
            allergies = form.allergies.data,
            medical_condition = form.medical_condition.data,
            miscarriage = form.miscarriage.data,
            still_birth = form.still_birth.data,
            premature_birth = form.premature_birth.data,
            pre_clamsia = form.pre_clamsia.data,
            gestation_diabetes = form.gestation_diabetes.data,
            hiv_status = form.hiv_status.data,
            sugar_levels = form.sugar_levels.data,
            weight = form.weight.data,
            prev_dev = form.prev_dev.data,
            id_number = form.id_number.data,
            marital_status =form.marital_status.data,
        )

        db.session.add(record)
        db.session.commit()
        db.session.add(record2)
        db.session.commit()

        flash("Record added", category="success")
    return render_template("add/new_med.html", form=form, name=name, last_name=last_name, admin=is_admin)

@add_bp.route("/scan", methods=["GET", "POST"])
def scan():
    name = session.get("name")
    last_name = session.get("last_name")
    is_admin = session.get("is_admin")
    form = AppointForm()

    if form.validate_on_submit():
        tyme = get_date()
        appointment = Appointment(
            name = form.name.data,
            mobile = form.mobile.data,
            email = form.email.data,
            date = tyme
        )

        db.session.add(appointment)
        db.session.commit()

        try:
            send_email(tyme, form.email.data)
        except:
            flash("No internet access", category="fail")

        flash("appointment will be booked and emailed to you shortly", category="success")


    return render_template("add/scan.html", form=form, name=name, last_name=last_name, admin=is_admin)

def get_date():
    time = datetime.now()
    timestamp = datetime.timestamp(time)
    
    return timestamp + 5

app/add/templates/add/add.html
{% extends "base.html" %}

{% block title %}<title>Add</title> {% endblock %}

{% block content %} 

{% endblock %}

app/add/templates/add/add_med.html
{% extends "base.html" %}

{% block title %}<title>Add medical history</title> {% endblock %}
{% block styles %}
<link rel="stylesheet" href="{{url_for('add_bp.static', filename='add/styles.css')}}">
{% endblock %}


{% block content %} 
<h1 class="h3 mb-4 ml-5 text-gray-800">Add medical records</h1>
<hr>
<div class= "alert-success" role="alert">{% with messages = get_flashed_messages() %}
  {% if messages %}
  <ul class="flashes">
      {% for message in messages %}
      <li>{{ message }}</li>
      {% endfor %}
  </ul>
  {% endif %}
  {% endwith %}</div>
<form action="{{ url_for('add_bp.add_med') }}" method="POST" novalidate class="row g-3 my-4 mr-5 ml-5">
  {{ form.csrf_token }}
    <div class="col-md-6">
      <label for="inputEmail4" class="form-label">{{ form.name.label }}</label>
      {{form.name(size=30, class="form-control", id="inputEmail4")}}
    </div>
    <div class="col-md-6">
      <label for="inputPassword4" class="form-label">{{ form.age.label }}</label>
      {{form.age(size=30, class="form-control", id="inputPassword4")}}
    </div>
    <div class="col-12 mt-3">
      <label for="inputAddress" class="form-label">{{ form.address.label }}</label>
      {{form.address(size=30, class="form-control", id="inputAddress", placeholder="1234 Main St")}}
    </div>
    <div class="col-md-6 mt-3">
      <label for="inputCity" class="form-label">{{ form.blood_type.label }}</label>
      {{form.blood_type(size=30, class="form-control", id="inputCity")}}
    </div>
    <div class="col-md-6 mt-3">
      <label for="number_children" class="form-label">{{ form.number_children.label }}</label>
      {{form.number_children(size=30, class="form-control", id="number_children")}}
    </div>
    <div class="col-md-6 mt-3">
      <label for="last_birth" class="form-label">{{ form.last_birth.label }}</label>
      {{form.last_birth(size=30, class="form-control", id="last_birth")}}
    </div>
    <div class="col-md-6 mt-3">
      <label for="allergies" class="form-label">{{ form.allergies.label }}</label>
      {{form.allergies(size=30, class="form-control", id="allergies")}}
    </div>
    <div class="col-md-6 mt-3">
      <label for="medical_condition" class="form-label">{{ form.medical_condition.label }}</label>
      {{form.medical_condition(size=30, class="form-control", id="medical_condition")}}
    </div>
    <div class="col-12 mt-3">
      <div class="form-check">
        <input class="form-check-input" type="checkbox" id="gridCheck">
        <label class="form-check-label" for="gridCheck">
          Check me out
        </label>
      </div>
    </div>
    <div class="col-12 mt-3">
      {{ form.submit(class="btn btn-primary") }}
    </div>
  </form>
  
{% endblock %}

app/add/templates/add/checkup.html
{% extends "base.html" %}

{% block title %}<title>Add checkup appointment</title> {% endblock %}
{% block styles %}
<link rel="stylesheet" href="{{url_for('add_bp.static', filename='add/styles.css')}}">
{% endblock %}
{

{% block content %} 
<h1 class="h3 mb-4 ml-5 text-gray-800">Add medical records</h1>
<hr>
<div class= "alert-success" role="alert">{% with messages = get_flashed_messages() %}
    {% if messages %}
    <ul class="flashes">
        {% for message in messages %}
        <li>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    {% endwith %}</div>
<div class="container mt-5 mb-5 d-flex justify-content-center">
    <div class="card px-1 py-4">
        <div class="card-body">          <form action="{{ url_for('add_bp.add') }}" method="POST" novalidate>
            {{ form.csrf_token }}
        <h6 class="card-title mb-3">This appointment is for</h6>
        <div class="d-flex flex-row"> <label class="radio mr-1"> <input type="radio" name="add" value="anz" checked> <span> <i class="fa fa-user"></i> {{name}} {{last_name}} </span> </label> <label class="radio"> <input type="radio" name="add" value="add"> <span> <i class="fa fa-plus-circle"></i> Add </span> </label> </div>
        <h6 class="information mt-4">Please provide following information about {{name}} {{last_name}}</h6>
        <div class="row">
            <div class="col-sm-12">
                <div class="form-group">
                    {{form.name(size=30, class="form-control",  placeholder="Name")}}
                 </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <div class="form-group">
                   
                    <div class="input-group">  {{form.mobile(size=30, class="form-control",  placeholder="Mobile")}} </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <div class="form-group">
                    <div class="input-group">  {{form.email(size=30, class="form-control",  placeholder="Email ID")}}</div>
                </div>
            </div>
        </div>
        <div class=" d-flex flex-column text-center px-5 mt-3 mb-3"> <small class="agree-text">By Booking this appointment you agree to the</small> <a href="#" class="terms">Terms & Conditions</a> </div>{{ form.submit(class="btn btn-primary btn-block confirm-button") }}
    </form>   <span>{% with messages = get_flashed_messages() %}
        {% if messages %}
        <ul class="flashes">
            {% for message in messages %}
            <li>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        {% endwith %}</span>     </div>
    </div>
</div>
{% endblock %}

app/add/templates/add/doctor.html
{% extends "base.html" %}

{% block title %}<title>Add doctors appointment</title> {% endblock %}
{% block styles %}
<link rel="stylesheet" href="{{url_for('add_bp.static', filename='add/styles.css')}}">
{% endblock %}


{% block content %} 
<h1 class="h3 mb-4 ml-5 text-gray-800">Add medical records</h1>
<hr>
<div class= "alert-success" role="alert">{% with messages = get_flashed_messages() %}
    {% if messages %}
    <ul class="flashes">
        {% for message in messages %}
        <li>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    {% endwith %}</div>
<div class="container mt-5 mb-5 d-flex justify-content-center">
    <div class="card px-1 py-4">
        <div class="card-body">
            <form action="{{ url_for('add_bp.add') }}" method="POST" novalidate>
                {{ form.csrf_token }}
            <h6 class="card-title mb-3">This appointment is for</h6>
            <div class="d-flex flex-row"> <label class="radio mr-1"> <input type="radio" name="add" value="anz" checked> <span> <i class="fa fa-user"></i> {{name}} {{last_name}} </span> </label> <label class="radio"> <input type="radio" name="add" value="add"> <span> <i class="fa fa-plus-circle"></i> Add </span> </label> </div>
            <h6 class="information mt-4">Please provide following information about {{name}} {{last_name}}</h6>
            <div class="row">
                <div class="col-sm-12">
                    <div class="form-group">
                        {{form.name(size=30, class="form-control",  placeholder="Name")}}
                     </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <div class="form-group">
                       
                        <div class="input-group">  {{form.mobile(size=30, class="form-control",  placeholder="Mobile")}} </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <div class="form-group">
                        <div class="input-group">  {{form.email(size=30, class="form-control",  placeholder="Email ID")}}</div>
                    </div>
                </div>
            </div>
            <div class=" d-flex flex-column text-center px-5 mt-3 mb-3"> <small class="agree-text">By Booking this appointment you agree to the</small> <a href="#" class="terms">Terms & Conditions</a> </div>{{ form.submit(class="btn btn-primary btn-block confirm-button") }}
        </form>  <span>{% with messages = get_flashed_messages() %}
            {% if messages %}
            <ul class="flashes">
                {% for message in messages %}
                <li>{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}
            {% endwith %}</span>      </div>
    </div>
</div>
{% endblock %}

app/add/templates/add/new_med.html
{% extends "base.html" %}

{% block styles %}
<link rel="stylesheet" href="{{url_for('add_bp.static', filename='add/styles.css')}}">

{% endblock %}

{% block title %}<title>New medical history</title> {% endblock %}

{% block content %} 
<h1 class="h3 mb-4 ml-5 text-gray-800">Add medical records</h1>
<hr>
<div class= "alert-success" role="alert">{% with messages = get_flashed_messages() %}
  {% if messages %}
  <ul class="flashes">
      {% for message in messages %}
      <li>{{ message }}</li>
      {% endfor %}
  </ul>
  {% endif %}
  {% endwith %}</div>
<form action="{{ url_for('add_bp.new_med') }}" method="POST" novalidate class="row g-3 my-4 mr-5 ml-5">
  {{ form.csrf_token }}
    <div class="col-md-6">
      <label for="inputEmail4" class="form-label">{{ form.name.label }}</label>
      {{form.name(size=30, class="form-control", id="inputEmail4")}}
    </div>
    <div class="col-md-6">
      <label for="inputPassword4" class="form-label">{{ form.age.label }}</label>
      {{form.age(size=30, class="form-control", id="inputPassword4")}}
    </div>
    <div class="col-12 mt-3">
      <label for="inputAddress" class="form-label">{{ form.address.label }}</label>
      {{form.address(size=30, class="form-control", id="inputAddress", placeholder="1234 Main St")}}
    </div>
    <div class="col-md-6 mt-3">
      <label for="inputCity" class="form-label">{{ form.blood_type.label }}</label>
      {{form.blood_type(size=30, class="form-control", id="inputCity")}}
    </div>
    <div class="col-md-6 mt-3">
      <label for="sbp" class="form-label">{{ form.systolic_BP.label }}</label>
      {{form.systolic_BP(size=30, class="form-control", id="sbp")}}
    </div>
    <div class="col-md-6 mt-3">
      <label for="diastolic_BP" class="form-label">{{ form.diastolic_BP.label }}</label>
      {{form.diastolic_BP(size=30, class="form-control", id="diastolic_BP")}}
    </div>
    <div class="col-md-6 mt-3">
      <label for="blood_sugar" class="form-label">{{ form.blood_sugar.label }}</label>
      {{form.blood_sugar(size=30, class="form-control", id="blood_sugar")}}
    </div>
    <div class="col-md-6 mt-3">
      <label for="body_temp" class="form-label">{{ form.body_temp.label }}</label>
      {{form.body_temp(size=30, class="form-control", id="body_temp")}}
    </div>
    <div class="col-md-6 mt-3">
      <label for="heart_rate" class="form-label">{{ form.heart_rate.label }}</label>
      {{form.heart_rate(size=30, class="form-control", id="heart_rate")}}
    </div>
    <div class="col-md-6 mt-3">
      <label for="number_children" class="form-label">{{ form.number_children.label }}</label>
      {{form.number_children(size=30, class="form-control", id="number_children")}}
    </div>
    <div class="col-md-6 mt-3">
      <label for="last_birth" class="form-label">{{ form.last_birth.label }}</label>
      {{form.last_birth(size=30, class="form-control", id="last_birth")}}
    </div>
    <div class="col-md-6 mt-3">
      <label for="allergies" class="form-label">{{ form.allergies.label }}</label>
      {{form.allergies(size=30, class="form-control", id="allergies")}}
    </div>
    <div class="col-md-6 mt-3">
      <label for="medical_condition" class="form-label">{{ form.medical_condition.label }}</label>
      {{form.medical_condition(size=30, class="form-control", id="medical_condition")}}
    </div>
    <div class="col-md-6 mt-3">
      <label for="miscarriage" class="form-label">{{ form.miscarriage.label }}</label>
      {{form.miscarriage(size=30, class="form-control", id="miscarriage")}}
    </div>
    <div class="col-md-6 mt-3">
      <label for="still_birth" class="form-label">{{ form.still_birth.label }}</label>
      {{form.still_birth(size=30, class="form-control", id="still_birth")}}
    </div>
    <div class="col-md-6 mt-3">
      <label for="premature_birth" class="form-label">{{ form.premature_birth.label }}</label>
      {{form.premature_birth(size=30, class="form-control", id="premature_birth")}}
    </div>
    <div class="col-md-6 mt-3">
      <label for="pre_clamsia" class="form-label">{{ form.pre_clamsia.label }}</label>
      {{form.pre_clamsia(size=30, class="form-control", id="pre_clamsia")}}
    </div>
    <div class="col-md-6 mt-3">
      <label for="gestation_diabetes" class="form-label">{{ form.gestation_diabetes.label }}</label>
      {{form.gestation_diabetes(size=30, class="form-control", id="gestation_diabetes")}}
    </div>
    <div class="col-md-6 mt-3">
      <label for="hiv_status" class="form-label">{{ form.hiv_status.label }}</label>
      {{form.hiv_status(size=30, class="form-control", id="hiv_status")}}
    </div>
    <div class="col-md-6 mt-3">
      <label for="sugar_levels" class="form-label">{{ form.sugar_levels.label }}</label>
      {{form.sugar_levels(size=30, class="form-control", id="sugar_levels")}}
    </div>
    <div class="col-md-6 mt-3">
      <label for="weight" class="form-label">{{ form.weight.label }}</label>
      {{form.weight(size=30, class="form-control", id="weight")}}
    </div>
    <div class="col-md-6 mt-3">
      <label for="prev_dev" class="form-label">{{ form.prev_dev.label }}</label>
      {{form.prev_dev(size=30, class="form-control", id="prev_dev")}}
    </div>
    <div class="col-md-6 mt-3">
      <label for="id_number" class="form-label">{{ form.id_number.label }}</label>
      {{form.id_number(size=30, class="form-control", id="id_number")}}
    </div>
    <div class="col-md-6 mt-3">
      <label for="marital_status" class="form-label">{{ form.marital_status.label }}</label>
      {{form.marital_status(size=30, class="form-control", id="marital_status")}}
    </div>
    <div class="col-12 mt-3">
      <div class="form-check">
        <input class="form-check-input" type="checkbox" id="gridCheck">
        <label class="form-check-label" for="gridCheck">
          Check me out
        </label>
      </div>
    </div>
    <div class="col-12 mt-3">
      {{ form.submit(class="btn btn-primary") }}
    </div>
  </form>
  <span>{% with messages = get_flashed_messages() %}
    {% if messages %}
    <ul class="flashes">
        {% for message in messages %}
        <li>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    {% endwith %}</span>
{% endblock %}

app/add/templates/add/scan.html
{% extends "base.html" %}

{% block styles %}
<link rel="stylesheet" href="{{url_for('add_bp.static', filename='add/styles.css')}}">
{% endblock %}
{% block title %}<title>Add Scan appointment </title> {% endblock %}

{% block content %} 
<h1 class="h3 mb-4 ml-5 text-gray-800">Add Scan appointment</h1>
<hr>
<div class= "alert-success" role="alert">{% with messages = get_flashed_messages() %}
    {% if messages %}
    <ul class="flashes">
        {% for message in messages %}
        <li>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    {% endwith %}</div>
<div class="container mt-5 mb-5 d-flex justify-content-center">
    <div class="card px-1 py-4">
        <div class="card-body">
            <form action="{{ url_for('add_bp.scan') }}" method="POST" novalidate>
                {{ form.csrf_token }}
            <h6 class="card-title mb-3">This appointment is for</h6>
            <div class="d-flex flex-row"> <label class="radio mr-1"> <input type="radio" name="add" value="anz" checked> <span> <i class="fa fa-user"></i> {{name}} {{last_name}} </span> </label> <label class="radio"> <input type="radio" name="add" value="add"> <span> <i class="fa fa-plus-circle"></i> Add </span> </label> </div>
            <h6 class="information mt-4">Please provide following information about {{name}} {{last_name}}</h6>
            <div class="row">
                <div class="col-sm-12">
                    <div class="form-group">
                        {{form.name(size=30, class="form-control",  placeholder="Name")}}
                     </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <div class="form-group">
                       
                        <div class="input-group">  {{form.mobile(size=30, class="form-control",  placeholder="Mobile")}} </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <div class="form-group">
                        <div class="input-group">  {{form.email(size=30, class="form-control",  placeholder="Email ID")}}</div>
                    </div>
                </div>
            </div>
            <div class=" d-flex flex-column text-center px-5 mt-3 mb-3"> <small class="agree-text">By Booking this appointment you agree to the</small> <a href="#" class="terms">Terms & Conditions</a> </div>{{ form.submit(class="btn btn-primary btn-block confirm-button") }}
        </form>
        <span>{% with messages = get_flashed_messages() %}
            {% if messages %}
            <ul class="flashes">
                {% for message in messages %}
                <li>{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}
            {% endwith %}</span>
        </div>
    </div>
</div>
{% endblock %}